export interface BusinessType {
  id: string;
  name: string;
  category: string;
  searchTerms: string[];
}

export const BUSINESS_CATEGORIES = [
  'Entertainment & Nightlife',
  'Home Services',
  'Professional Services',
  'Health & Wellness',
  'Beauty & Personal Care',
  'Automotive',
  'Food & Hospitality',
  'Fitness & Recreation',
  'Pet Services',
  'Cleaning & Maintenance',
  'Education & Childcare',
  'Events & Creative',
  'Specialty Trades',
  'B2B Services',
  'Senior Services',
  'Wedding & Bridal',
  'Specialty Retail',
  'Travel & Transport',
  'Legal Support',
  'Agriculture & Rural',
] as const;

export const BUSINESS_TYPES: BusinessType[] = [
  // ── Entertainment & Nightlife ──────────────────────────────────────────────
  { id: 'live_music_venue', name: 'Live Music Venue', category: 'Entertainment & Nightlife', searchTerms: ['live music venue', 'live music bar', 'small concert venue', 'music club'] },
  { id: 'music_bar', name: 'Music Bar / Lounge', category: 'Entertainment & Nightlife', searchTerms: ['music bar', 'jazz bar', 'blues bar', 'live music lounge'] },
  { id: 'concert_hall', name: 'Concert Hall', category: 'Entertainment & Nightlife', searchTerms: ['concert hall', 'performing arts center', 'music hall'] },
  { id: 'nightclub', name: 'Nightclub', category: 'Entertainment & Nightlife', searchTerms: ['nightclub', 'dance club', 'DJ venue'] },
  { id: 'brewery_venue', name: 'Brewery / Taproom with Live Music', category: 'Entertainment & Nightlife', searchTerms: ['brewery live music', 'taproom live entertainment', 'craft beer live music'] },
  { id: 'comedy_club', name: 'Comedy Club', category: 'Entertainment & Nightlife', searchTerms: ['comedy club', 'stand up comedy venue', 'comedy show venue'] },
  { id: 'karaoke_bar', name: 'Karaoke Bar', category: 'Entertainment & Nightlife', searchTerms: ['karaoke bar', 'karaoke night', 'karaoke lounge'] },
  { id: 'wine_bar', name: 'Wine Bar', category: 'Entertainment & Nightlife', searchTerms: ['wine bar', 'wine tasting room', 'wine lounge'] },
  { id: 'escape_room', name: 'Escape Room', category: 'Entertainment & Nightlife', searchTerms: ['escape room', 'escape game', 'puzzle room'] },
  { id: 'bowling_alley', name: 'Bowling Alley', category: 'Entertainment & Nightlife', searchTerms: ['bowling alley', 'bowling center', 'bowling lanes'] },

  // ── Home Services ──────────────────────────────────────────────────────────
  { id: 'plumber', name: 'Plumber', category: 'Home Services', searchTerms: ['plumbing service', 'plumber near me', 'plumbing contractor'] },
  { id: 'electrician', name: 'Electrician', category: 'Home Services', searchTerms: ['electrician service', 'electrical contractor', 'electrician near me'] },
  { id: 'hvac', name: 'HVAC Technician', category: 'Home Services', searchTerms: ['HVAC service', 'heating and cooling', 'air conditioning repair'] },
  { id: 'landscaper', name: 'Landscaper', category: 'Home Services', searchTerms: ['landscaping service', 'lawn care service', 'landscaper near me'] },
  { id: 'painter', name: 'Painter / Decorator', category: 'Home Services', searchTerms: ['house painter', 'painting contractor', 'interior decorator'] },
  { id: 'roofer', name: 'Roofer', category: 'Home Services', searchTerms: ['roofing contractor', 'roof repair service', 'roofer near me'] },
  { id: 'kitchen_installer', name: 'Kitchen Installer', category: 'Home Services', searchTerms: ['kitchen remodel', 'kitchen installer', 'kitchen renovation contractor'] },
  { id: 'bathroom_remodeler', name: 'Bathroom Remodeler', category: 'Home Services', searchTerms: ['bathroom remodel', 'bathroom renovation', 'bathroom contractor'] },
  { id: 'flooring', name: 'Flooring Specialist', category: 'Home Services', searchTerms: ['flooring installer', 'hardwood flooring', 'flooring contractor'] },
  { id: 'fencing', name: 'Fencing Contractor', category: 'Home Services', searchTerms: ['fence installer', 'fencing company', 'fence contractor'] },
  { id: 'garage_door', name: 'Garage Door Service', category: 'Home Services', searchTerms: ['garage door repair', 'garage door installer', 'garage door service'] },
  { id: 'handyman', name: 'Handyman', category: 'Home Services', searchTerms: ['handyman service', 'home repair service', 'handyman near me'] },
  { id: 'general_contractor', name: 'General Contractor', category: 'Home Services', searchTerms: ['general contractor', 'home builder', 'construction contractor'] },
  { id: 'drywall', name: 'Drywall Contractor', category: 'Home Services', searchTerms: ['drywall contractor', 'drywall repair', 'drywall installer'] },
  { id: 'concrete', name: 'Concrete Contractor', category: 'Home Services', searchTerms: ['concrete contractor', 'concrete work', 'concrete driveway'] },
  { id: 'deck_builder', name: 'Deck / Patio Builder', category: 'Home Services', searchTerms: ['deck builder', 'patio contractor', 'outdoor deck construction'] },
  { id: 'siding', name: 'Siding Contractor', category: 'Home Services', searchTerms: ['siding contractor', 'siding installer', 'vinyl siding'] },
  { id: 'gutter', name: 'Gutter Service', category: 'Home Services', searchTerms: ['gutter installation', 'gutter cleaning', 'gutter repair'] },
  { id: 'insulation', name: 'Insulation Contractor', category: 'Home Services', searchTerms: ['insulation contractor', 'spray foam insulation', 'home insulation'] },
  { id: 'waterproofing', name: 'Waterproofing / Foundation', category: 'Home Services', searchTerms: ['basement waterproofing', 'foundation repair', 'waterproofing contractor'] },
  { id: 'solar_installer', name: 'Solar Panel Installer', category: 'Home Services', searchTerms: ['solar panel installer', 'solar energy company', 'residential solar'] },
  { id: 'home_inspector', name: 'Home Inspector', category: 'Home Services', searchTerms: ['home inspection', 'home inspector near me', 'property inspection'] },
  { id: 'window_installer', name: 'Window Installer', category: 'Home Services', searchTerms: ['window replacement', 'window installer', 'new windows'] },
  { id: 'closet_organizer', name: 'Closet / Organization', category: 'Home Services', searchTerms: ['closet organizer', 'custom closets', 'home organization'] },
  { id: 'interior_designer', name: 'Interior Designer', category: 'Home Services', searchTerms: ['interior designer', 'interior design service', 'home decorator'] },
  { id: 'septic_service', name: 'Septic Service', category: 'Home Services', searchTerms: ['septic tank service', 'septic pumping', 'septic system repair'] },
  { id: 'well_drilling', name: 'Well Drilling / Water', category: 'Home Services', searchTerms: ['well drilling', 'water well service', 'well pump repair'] },
  { id: 'chimney_sweep', name: 'Chimney Sweep', category: 'Home Services', searchTerms: ['chimney sweep', 'chimney cleaning', 'chimney repair'] },

  // ── Professional Services ──────────────────────────────────────────────────
  { id: 'accountant', name: 'Accountant / CPA', category: 'Professional Services', searchTerms: ['accounting firm', 'CPA near me', 'tax accountant'] },
  { id: 'lawyer', name: 'Lawyer / Attorney', category: 'Professional Services', searchTerms: ['law firm', 'attorney near me', 'legal services'] },
  { id: 'real_estate', name: 'Real Estate Agent', category: 'Professional Services', searchTerms: ['real estate agent', 'realtor near me', 'real estate broker'] },
  { id: 'insurance', name: 'Insurance Agent', category: 'Professional Services', searchTerms: ['insurance agency', 'insurance broker', 'insurance agent near me'] },
  { id: 'financial_advisor', name: 'Financial Advisor', category: 'Professional Services', searchTerms: ['financial advisor', 'financial planner', 'wealth management'] },
  { id: 'mortgage_broker', name: 'Mortgage Broker', category: 'Professional Services', searchTerms: ['mortgage broker', 'mortgage lender', 'home loan officer'] },
  { id: 'notary', name: 'Notary Public', category: 'Professional Services', searchTerms: ['notary public', 'notary service', 'mobile notary'] },
  { id: 'tax_preparer', name: 'Tax Preparer', category: 'Professional Services', searchTerms: ['tax preparation service', 'tax preparer', 'tax filing service'] },
  { id: 'immigration_lawyer', name: 'Immigration Lawyer', category: 'Professional Services', searchTerms: ['immigration lawyer', 'immigration attorney', 'visa lawyer'] },
  { id: 'family_lawyer', name: 'Family Lawyer', category: 'Professional Services', searchTerms: ['family law attorney', 'divorce lawyer', 'custody lawyer'] },
  { id: 'estate_planning', name: 'Estate Planning Attorney', category: 'Professional Services', searchTerms: ['estate planning attorney', 'wills and trusts', 'estate lawyer'] },
  { id: 'personal_injury', name: 'Personal Injury Lawyer', category: 'Professional Services', searchTerms: ['personal injury lawyer', 'accident attorney', 'injury claim lawyer'] },
  { id: 'property_manager', name: 'Property Manager', category: 'Professional Services', searchTerms: ['property management company', 'rental management', 'property manager'] },
  { id: 'home_appraiser', name: 'Home Appraiser', category: 'Professional Services', searchTerms: ['home appraiser', 'property appraisal', 'real estate appraisal'] },
  { id: 'title_company', name: 'Title Company', category: 'Professional Services', searchTerms: ['title company', 'title insurance', 'title search service'] },

  // ── Health & Wellness ──────────────────────────────────────────────────────
  { id: 'dentist', name: 'Dentist', category: 'Health & Wellness', searchTerms: ['dental office', 'dentist near me', 'dental clinic'] },
  { id: 'chiropractor', name: 'Chiropractor', category: 'Health & Wellness', searchTerms: ['chiropractor near me', 'chiropractic clinic', 'back pain specialist'] },
  { id: 'physiotherapist', name: 'Physiotherapist', category: 'Health & Wellness', searchTerms: ['physical therapy', 'physiotherapist near me', 'PT clinic'] },
  { id: 'optometrist', name: 'Optometrist', category: 'Health & Wellness', searchTerms: ['optometrist near me', 'eye doctor', 'eye care center'] },
  { id: 'massage_therapist', name: 'Massage Therapist', category: 'Health & Wellness', searchTerms: ['massage therapy', 'massage therapist near me', 'therapeutic massage'] },
  { id: 'acupuncturist', name: 'Acupuncturist', category: 'Health & Wellness', searchTerms: ['acupuncture clinic', 'acupuncturist near me', 'acupuncture treatment'] },
  { id: 'therapist', name: 'Therapist / Counselor', category: 'Health & Wellness', searchTerms: ['therapist near me', 'counselor', 'mental health therapist'] },
  { id: 'psychologist', name: 'Psychologist', category: 'Health & Wellness', searchTerms: ['psychologist near me', 'psychology practice', 'clinical psychologist'] },
  { id: 'dermatologist', name: 'Dermatologist', category: 'Health & Wellness', searchTerms: ['dermatologist near me', 'skin doctor', 'dermatology clinic'] },
  { id: 'podiatrist', name: 'Podiatrist', category: 'Health & Wellness', searchTerms: ['podiatrist near me', 'foot doctor', 'podiatry clinic'] },
  { id: 'audiologist', name: 'Audiologist', category: 'Health & Wellness', searchTerms: ['audiologist near me', 'hearing specialist', 'hearing aid center'] },
  { id: 'orthodontist', name: 'Orthodontist', category: 'Health & Wellness', searchTerms: ['orthodontist near me', 'braces', 'invisalign provider'] },
  { id: 'oral_surgeon', name: 'Oral Surgeon', category: 'Health & Wellness', searchTerms: ['oral surgeon', 'wisdom teeth removal', 'dental surgery'] },
  { id: 'pediatric_dentist', name: 'Pediatric Dentist', category: 'Health & Wellness', searchTerms: ['pediatric dentist', 'kids dentist', 'children dental'] },
  { id: 'nutritionist', name: 'Nutritionist / Dietitian', category: 'Health & Wellness', searchTerms: ['nutritionist near me', 'dietitian', 'nutrition counseling'] },
  { id: 'speech_therapist', name: 'Speech Therapist', category: 'Health & Wellness', searchTerms: ['speech therapist', 'speech pathologist', 'speech therapy'] },
  { id: 'occupational_therapist', name: 'Occupational Therapist', category: 'Health & Wellness', searchTerms: ['occupational therapy', 'OT near me', 'occupational therapist'] },
  { id: 'naturopath', name: 'Naturopath', category: 'Health & Wellness', searchTerms: ['naturopathic doctor', 'naturopath near me', 'holistic medicine'] },
  { id: 'urgent_care', name: 'Urgent Care Clinic', category: 'Health & Wellness', searchTerms: ['urgent care near me', 'walk-in clinic', 'urgent care center'] },
  { id: 'med_spa', name: 'Medical Spa', category: 'Health & Wellness', searchTerms: ['medical spa', 'med spa near me', 'aesthetic clinic', 'botox clinic'] },

  // ── Beauty & Personal Care ─────────────────────────────────────────────────
  { id: 'hair_salon', name: 'Hair Salon', category: 'Beauty & Personal Care', searchTerms: ['hair salon near me', 'hairdresser', 'hair stylist'] },
  { id: 'barber', name: 'Barber Shop', category: 'Beauty & Personal Care', searchTerms: ['barber shop near me', 'mens haircut', 'barber'] },
  { id: 'nail_salon', name: 'Nail Salon', category: 'Beauty & Personal Care', searchTerms: ['nail salon near me', 'manicure pedicure', 'nail spa'] },
  { id: 'spa', name: 'Day Spa', category: 'Beauty & Personal Care', searchTerms: ['day spa near me', 'spa services', 'facial treatment'] },
  { id: 'tattoo', name: 'Tattoo Studio', category: 'Beauty & Personal Care', searchTerms: ['tattoo shop near me', 'tattoo artist', 'tattoo studio'] },
  { id: 'lash_brow', name: 'Lash & Brow Studio', category: 'Beauty & Personal Care', searchTerms: ['lash extensions', 'brow bar', 'eyelash salon'] },
  { id: 'waxing', name: 'Waxing Salon', category: 'Beauty & Personal Care', searchTerms: ['waxing salon', 'Brazilian wax', 'waxing near me'] },
  { id: 'tanning', name: 'Tanning Salon', category: 'Beauty & Personal Care', searchTerms: ['tanning salon', 'spray tan', 'tanning bed near me'] },
  { id: 'makeup_artist', name: 'Makeup Artist', category: 'Beauty & Personal Care', searchTerms: ['makeup artist near me', 'bridal makeup', 'MUA'] },
  { id: 'piercing_studio', name: 'Piercing Studio', category: 'Beauty & Personal Care', searchTerms: ['piercing studio', 'body piercing', 'ear piercing near me'] },
  { id: 'hair_removal', name: 'Laser Hair Removal', category: 'Beauty & Personal Care', searchTerms: ['laser hair removal', 'electrolysis', 'hair removal clinic'] },
  { id: 'teeth_whitening', name: 'Teeth Whitening', category: 'Beauty & Personal Care', searchTerms: ['teeth whitening', 'cosmetic teeth whitening', 'teeth whitening near me'] },

  // ── Automotive ─────────────────────────────────────────────────────────────
  { id: 'auto_mechanic', name: 'Auto Mechanic', category: 'Automotive', searchTerms: ['auto repair shop', 'car mechanic near me', 'auto service center'] },
  { id: 'auto_body', name: 'Auto Body Shop', category: 'Automotive', searchTerms: ['auto body repair', 'collision repair', 'auto body shop near me'] },
  { id: 'auto_detailing', name: 'Auto Detailing', category: 'Automotive', searchTerms: ['car detailing service', 'auto detailing near me', 'mobile car wash'] },
  { id: 'tire_shop', name: 'Tire Shop', category: 'Automotive', searchTerms: ['tire shop near me', 'tire service', 'tire dealer'] },
  { id: 'oil_change', name: 'Oil Change / Lube', category: 'Automotive', searchTerms: ['oil change near me', 'quick lube', 'oil change service'] },
  { id: 'transmission', name: 'Transmission Shop', category: 'Automotive', searchTerms: ['transmission repair', 'transmission shop', 'transmission service'] },
  { id: 'auto_glass', name: 'Auto Glass Repair', category: 'Automotive', searchTerms: ['windshield repair', 'auto glass replacement', 'auto glass near me'] },
  { id: 'auto_electric', name: 'Auto Electrician', category: 'Automotive', searchTerms: ['auto electrician', 'car electrical repair', 'vehicle electrical'] },
  { id: 'brake_service', name: 'Brake Service', category: 'Automotive', searchTerms: ['brake repair', 'brake service near me', 'brake shop'] },
  { id: 'towing', name: 'Towing Service', category: 'Automotive', searchTerms: ['towing service', 'tow truck near me', 'roadside assistance'] },
  { id: 'motorcycle_shop', name: 'Motorcycle Shop', category: 'Automotive', searchTerms: ['motorcycle repair', 'motorcycle shop', 'motorcycle mechanic'] },
  { id: 'boat_repair', name: 'Boat / Marine Repair', category: 'Automotive', searchTerms: ['boat repair', 'marine mechanic', 'boat service'] },
  { id: 'rv_repair', name: 'RV Repair', category: 'Automotive', searchTerms: ['RV repair', 'RV service', 'motorhome repair'] },
  { id: 'car_wash', name: 'Car Wash', category: 'Automotive', searchTerms: ['car wash near me', 'hand car wash', 'car wash service'] },
  { id: 'upholstery_auto', name: 'Auto Upholstery', category: 'Automotive', searchTerms: ['auto upholstery', 'car seat repair', 'vehicle upholstery'] },

  // ── Food & Hospitality ─────────────────────────────────────────────────────
  { id: 'caterer', name: 'Caterer', category: 'Food & Hospitality', searchTerms: ['catering service', 'event catering', 'caterer near me'] },
  { id: 'bakery', name: 'Bakery', category: 'Food & Hospitality', searchTerms: ['bakery near me', 'custom cakes', 'local bakery'] },
  { id: 'food_truck', name: 'Food Truck', category: 'Food & Hospitality', searchTerms: ['food truck', 'mobile food vendor', 'food truck catering'] },
  { id: 'coffee_shop', name: 'Coffee Shop / Cafe', category: 'Food & Hospitality', searchTerms: ['coffee shop', 'local cafe', 'specialty coffee'] },
  { id: 'restaurant', name: 'Restaurant', category: 'Food & Hospitality', searchTerms: ['restaurant near me', 'local restaurant', 'family restaurant'] },
  { id: 'pizza_shop', name: 'Pizza Shop', category: 'Food & Hospitality', searchTerms: ['pizza shop', 'local pizza', 'pizza delivery'] },
  { id: 'ice_cream', name: 'Ice Cream Shop', category: 'Food & Hospitality', searchTerms: ['ice cream shop', 'ice cream parlor', 'gelato shop'] },
  { id: 'juice_bar', name: 'Juice / Smoothie Bar', category: 'Food & Hospitality', searchTerms: ['juice bar', 'smoothie bar', 'cold pressed juice'] },
  { id: 'meal_prep', name: 'Meal Prep Service', category: 'Food & Hospitality', searchTerms: ['meal prep service', 'meal delivery', 'prepared meals'] },
  { id: 'private_chef', name: 'Private Chef', category: 'Food & Hospitality', searchTerms: ['private chef', 'personal chef', 'in-home chef'] },
  { id: 'wedding_venue', name: 'Wedding Venue', category: 'Food & Hospitality', searchTerms: ['wedding venue', 'event venue', 'reception hall'] },
  { id: 'bed_breakfast', name: 'Bed & Breakfast', category: 'Food & Hospitality', searchTerms: ['bed and breakfast', 'B&B', 'boutique inn'] },

  // ── Fitness & Recreation ───────────────────────────────────────────────────
  { id: 'personal_trainer', name: 'Personal Trainer', category: 'Fitness & Recreation', searchTerms: ['personal trainer near me', 'fitness trainer', 'personal training'] },
  { id: 'yoga_studio', name: 'Yoga Studio', category: 'Fitness & Recreation', searchTerms: ['yoga studio near me', 'yoga class', 'hot yoga'] },
  { id: 'pilates', name: 'Pilates Studio', category: 'Fitness & Recreation', searchTerms: ['pilates studio', 'pilates class', 'reformer pilates'] },
  { id: 'crossfit', name: 'CrossFit Gym', category: 'Fitness & Recreation', searchTerms: ['CrossFit gym', 'CrossFit box', 'CrossFit near me'] },
  { id: 'martial_arts', name: 'Martial Arts Studio', category: 'Fitness & Recreation', searchTerms: ['martial arts school', 'karate dojo', 'MMA gym'] },
  { id: 'dance_studio', name: 'Dance Studio', category: 'Fitness & Recreation', searchTerms: ['dance studio', 'dance class', 'dance lessons'] },
  { id: 'swim_school', name: 'Swim School', category: 'Fitness & Recreation', searchTerms: ['swim lessons', 'swim school', 'swimming classes'] },
  { id: 'rock_climbing', name: 'Rock Climbing Gym', category: 'Fitness & Recreation', searchTerms: ['rock climbing gym', 'bouldering gym', 'climbing center'] },
  { id: 'boxing_gym', name: 'Boxing / Kickboxing Gym', category: 'Fitness & Recreation', searchTerms: ['boxing gym', 'kickboxing class', 'boxing training'] },
  { id: 'golf_instructor', name: 'Golf Instructor', category: 'Fitness & Recreation', searchTerms: ['golf lessons', 'golf instructor', 'golf coaching'] },
  { id: 'tennis_coach', name: 'Tennis Coach', category: 'Fitness & Recreation', searchTerms: ['tennis lessons', 'tennis coach', 'tennis instructor'] },
  { id: 'gym', name: 'Local Gym / Fitness Center', category: 'Fitness & Recreation', searchTerms: ['gym near me', 'fitness center', 'local gym'] },

  // ── Pet Services ───────────────────────────────────────────────────────────
  { id: 'veterinarian', name: 'Veterinarian', category: 'Pet Services', searchTerms: ['vet near me', 'veterinary clinic', 'animal hospital'] },
  { id: 'pet_groomer', name: 'Pet Groomer', category: 'Pet Services', searchTerms: ['pet grooming', 'dog groomer near me', 'pet grooming salon'] },
  { id: 'dog_walker', name: 'Dog Walker / Pet Sitter', category: 'Pet Services', searchTerms: ['dog walking service', 'pet sitter near me', 'dog walker'] },
  { id: 'dog_trainer', name: 'Dog Trainer', category: 'Pet Services', searchTerms: ['dog trainer near me', 'puppy training', 'dog obedience class'] },
  { id: 'pet_boarding', name: 'Pet Boarding / Kennel', category: 'Pet Services', searchTerms: ['pet boarding', 'dog kennel', 'dog boarding near me'] },
  { id: 'pet_store', name: 'Pet Store', category: 'Pet Services', searchTerms: ['pet store near me', 'local pet shop', 'pet supplies'] },
  { id: 'mobile_vet', name: 'Mobile Vet', category: 'Pet Services', searchTerms: ['mobile veterinarian', 'house call vet', 'mobile vet near me'] },
  { id: 'pet_photography', name: 'Pet Photographer', category: 'Pet Services', searchTerms: ['pet photographer', 'pet photography', 'dog photographer'] },

  // ── Cleaning & Maintenance ─────────────────────────────────────────────────
  { id: 'house_cleaner', name: 'House Cleaner', category: 'Cleaning & Maintenance', searchTerms: ['house cleaning service', 'maid service', 'home cleaning'] },
  { id: 'carpet_cleaner', name: 'Carpet Cleaner', category: 'Cleaning & Maintenance', searchTerms: ['carpet cleaning service', 'carpet cleaner near me', 'upholstery cleaning'] },
  { id: 'window_cleaner', name: 'Window Cleaner', category: 'Cleaning & Maintenance', searchTerms: ['window cleaning service', 'window washer', 'window cleaner near me'] },
  { id: 'pest_control', name: 'Pest Control', category: 'Cleaning & Maintenance', searchTerms: ['pest control service', 'exterminator near me', 'pest removal'] },
  { id: 'pool_service', name: 'Pool Service', category: 'Cleaning & Maintenance', searchTerms: ['pool cleaning service', 'pool maintenance', 'pool service near me'] },
  { id: 'pressure_washing', name: 'Pressure Washing', category: 'Cleaning & Maintenance', searchTerms: ['pressure washing service', 'power washing', 'pressure wash near me'] },
  { id: 'junk_removal', name: 'Junk Removal', category: 'Cleaning & Maintenance', searchTerms: ['junk removal service', 'junk hauling', 'trash removal'] },
  { id: 'air_duct', name: 'Air Duct Cleaning', category: 'Cleaning & Maintenance', searchTerms: ['air duct cleaning', 'dryer vent cleaning', 'duct cleaning service'] },
  { id: 'lawn_mowing', name: 'Lawn Mowing Service', category: 'Cleaning & Maintenance', searchTerms: ['lawn mowing service', 'grass cutting', 'lawn care'] },
  { id: 'snow_removal', name: 'Snow Removal', category: 'Cleaning & Maintenance', searchTerms: ['snow removal service', 'snow plowing', 'ice removal'] },

  // ── Education & Childcare ──────────────────────────────────────────────────
  { id: 'tutor', name: 'Tutor', category: 'Education & Childcare', searchTerms: ['tutoring service', 'private tutor', 'academic tutoring'] },
  { id: 'daycare', name: 'Daycare / Childcare', category: 'Education & Childcare', searchTerms: ['daycare near me', 'childcare center', 'preschool'] },
  { id: 'driving_school', name: 'Driving School', category: 'Education & Childcare', searchTerms: ['driving school near me', 'driving lessons', 'driving instructor'] },
  { id: 'music_teacher', name: 'Music Teacher / Lessons', category: 'Education & Childcare', searchTerms: ['music lessons', 'piano teacher', 'guitar lessons'] },
  { id: 'art_school', name: 'Art School / Classes', category: 'Education & Childcare', searchTerms: ['art classes', 'painting class', 'art school near me'] },
  { id: 'language_school', name: 'Language School', category: 'Education & Childcare', searchTerms: ['language school', 'ESL classes', 'language lessons'] },
  { id: 'test_prep', name: 'Test Prep / SAT Tutor', category: 'Education & Childcare', searchTerms: ['SAT tutor', 'test prep', 'ACT tutoring'] },
  { id: 'montessori', name: 'Montessori School', category: 'Education & Childcare', searchTerms: ['Montessori school', 'Montessori preschool', 'Montessori near me'] },
  { id: 'after_school', name: 'After School Program', category: 'Education & Childcare', searchTerms: ['after school program', 'after school care', 'kids activities'] },
  { id: 'coding_school', name: 'Coding / STEM School', category: 'Education & Childcare', searchTerms: ['kids coding class', 'STEM school', 'robotics class'] },

  // ── Events & Creative ──────────────────────────────────────────────────────
  { id: 'photographer', name: 'Photographer', category: 'Events & Creative', searchTerms: ['photographer near me', 'photography studio', 'event photographer'] },
  { id: 'videographer', name: 'Videographer', category: 'Events & Creative', searchTerms: ['videographer near me', 'wedding videographer', 'video production'] },
  { id: 'event_planner', name: 'Event Planner', category: 'Events & Creative', searchTerms: ['event planner near me', 'wedding planner', 'event planning service'] },
  { id: 'florist', name: 'Florist', category: 'Events & Creative', searchTerms: ['florist near me', 'flower shop', 'wedding flowers'] },
  { id: 'dj', name: 'DJ / Entertainment', category: 'Events & Creative', searchTerms: ['DJ near me', 'wedding DJ', 'party DJ'] },
  { id: 'party_rental', name: 'Party Rental', category: 'Events & Creative', searchTerms: ['party rental', 'event rental', 'tent rental'] },
  { id: 'balloon_decor', name: 'Balloon / Event Decor', category: 'Events & Creative', searchTerms: ['balloon decor', 'event decoration', 'party decorations'] },
  { id: 'print_shop', name: 'Print Shop', category: 'Events & Creative', searchTerms: ['print shop near me', 'printing service', 'custom printing'] },
  { id: 'graphic_designer', name: 'Graphic Designer', category: 'Events & Creative', searchTerms: ['graphic designer', 'logo design', 'graphic design service'] },
  { id: 'sign_shop', name: 'Sign Shop', category: 'Events & Creative', searchTerms: ['sign shop', 'custom signs', 'business signs'] },
  { id: 'embroidery', name: 'Embroidery / Screen Print', category: 'Events & Creative', searchTerms: ['embroidery shop', 'screen printing', 'custom t-shirts'] },

  // ── Specialty Trades ───────────────────────────────────────────────────────
  { id: 'locksmith', name: 'Locksmith', category: 'Specialty Trades', searchTerms: ['locksmith near me', 'locksmith service', 'emergency locksmith'] },
  { id: 'appliance_repair', name: 'Appliance Repair', category: 'Specialty Trades', searchTerms: ['appliance repair service', 'appliance technician', 'washer dryer repair'] },
  { id: 'tree_service', name: 'Tree Service', category: 'Specialty Trades', searchTerms: ['tree removal service', 'tree trimming', 'arborist near me'] },
  { id: 'moving_company', name: 'Moving Company', category: 'Specialty Trades', searchTerms: ['moving company near me', 'local movers', 'moving service'] },
  { id: 'storage', name: 'Storage Facility', category: 'Specialty Trades', searchTerms: ['storage units', 'self storage', 'storage facility near me'] },
  { id: 'furniture_repair', name: 'Furniture Repair / Refinish', category: 'Specialty Trades', searchTerms: ['furniture repair', 'furniture refinishing', 'furniture restoration'] },
  { id: 'upholstery', name: 'Upholstery Shop', category: 'Specialty Trades', searchTerms: ['upholstery service', 'furniture upholstery', 'reupholstery'] },
  { id: 'tailor', name: 'Tailor / Alterations', category: 'Specialty Trades', searchTerms: ['tailor near me', 'alterations', 'clothing alterations'] },
  { id: 'shoe_repair', name: 'Shoe Repair', category: 'Specialty Trades', searchTerms: ['shoe repair', 'cobbler near me', 'shoe cobbler'] },
  { id: 'dry_cleaner', name: 'Dry Cleaner', category: 'Specialty Trades', searchTerms: ['dry cleaner near me', 'dry cleaning service', 'laundry service'] },
  { id: 'jeweler', name: 'Jeweler', category: 'Specialty Trades', searchTerms: ['jeweler near me', 'jewelry repair', 'custom jewelry'] },
  { id: 'watch_repair', name: 'Watch Repair', category: 'Specialty Trades', searchTerms: ['watch repair', 'watch service', 'clock repair'] },
  { id: 'computer_repair', name: 'Computer Repair', category: 'Specialty Trades', searchTerms: ['computer repair', 'PC repair near me', 'laptop repair'] },
  { id: 'phone_repair', name: 'Phone Repair', category: 'Specialty Trades', searchTerms: ['phone repair near me', 'iPhone repair', 'screen repair'] },
  { id: 'electronics_repair', name: 'Electronics Repair', category: 'Specialty Trades', searchTerms: ['electronics repair', 'TV repair', 'audio equipment repair'] },
  { id: 'small_engine', name: 'Small Engine Repair', category: 'Specialty Trades', searchTerms: ['small engine repair', 'lawn mower repair', 'chainsaw repair'] },
  { id: 'welder', name: 'Welder / Fabricator', category: 'Specialty Trades', searchTerms: ['welding service', 'metal fabrication', 'welder near me'] },
  { id: 'glass_repair', name: 'Glass Repair / Glazier', category: 'Specialty Trades', searchTerms: ['glass repair', 'window glass replacement', 'glazier near me'] },
  { id: 'courier', name: 'Courier / Delivery Service', category: 'Specialty Trades', searchTerms: ['courier service', 'local delivery', 'same day delivery'] },

  // ── B2B Services ───────────────────────────────────────────────────────────
  { id: 'commercial_cleaner', name: 'Commercial Cleaner', category: 'B2B Services', searchTerms: ['commercial cleaning', 'office cleaning service', 'janitorial service'] },
  { id: 'it_support', name: 'IT Support / MSP', category: 'B2B Services', searchTerms: ['IT support company', 'managed IT service', 'business IT support'] },
  { id: 'web_developer', name: 'Web Developer / Agency', category: 'B2B Services', searchTerms: ['web development company', 'website designer', 'web developer'] },
  { id: 'marketing_agency', name: 'Marketing Agency', category: 'B2B Services', searchTerms: ['marketing agency', 'digital marketing', 'marketing company'] },
  { id: 'seo_company', name: 'SEO Company', category: 'B2B Services', searchTerms: ['SEO company', 'SEO service', 'search engine optimization'] },
  { id: 'bookkeeper', name: 'Bookkeeper', category: 'B2B Services', searchTerms: ['bookkeeping service', 'bookkeeper near me', 'small business bookkeeping'] },
  { id: 'payroll_service', name: 'Payroll Service', category: 'B2B Services', searchTerms: ['payroll service', 'payroll company', 'payroll processing'] },
  { id: 'staffing_agency', name: 'Staffing Agency', category: 'B2B Services', searchTerms: ['staffing agency', 'temp agency', 'employment agency'] },
  { id: 'commercial_hvac', name: 'Commercial HVAC', category: 'B2B Services', searchTerms: ['commercial HVAC', 'commercial air conditioning', 'commercial heating'] },
  { id: 'commercial_plumber', name: 'Commercial Plumber', category: 'B2B Services', searchTerms: ['commercial plumbing', 'commercial plumber', 'commercial plumbing contractor'] },
  { id: 'commercial_electrician', name: 'Commercial Electrician', category: 'B2B Services', searchTerms: ['commercial electrician', 'commercial electrical contractor', 'business electrician'] },
  { id: 'security_system', name: 'Security System Installer', category: 'B2B Services', searchTerms: ['security system installer', 'business security', 'alarm system installation'] },
  { id: 'business_consultant', name: 'Business Consultant', category: 'B2B Services', searchTerms: ['business consultant', 'small business consulting', 'management consultant'] },
  { id: 'copier_printer', name: 'Copier / Printer Service', category: 'B2B Services', searchTerms: ['copier service', 'office printer repair', 'copier lease'] },
  { id: 'commercial_pest', name: 'Commercial Pest Control', category: 'B2B Services', searchTerms: ['commercial pest control', 'business pest control', 'restaurant pest control'] },
  { id: 'fire_protection', name: 'Fire Protection', category: 'B2B Services', searchTerms: ['fire protection service', 'fire extinguisher service', 'fire alarm installation'] },
  { id: 'commercial_landscape', name: 'Commercial Landscaping', category: 'B2B Services', searchTerms: ['commercial landscaping', 'commercial lawn care', 'business landscaping'] },
  { id: 'office_furniture', name: 'Office Furniture', category: 'B2B Services', searchTerms: ['office furniture store', 'office furniture dealer', 'business furniture'] },
  { id: 'answering_service', name: 'Answering / Call Service', category: 'B2B Services', searchTerms: ['answering service', 'business call center', 'virtual receptionist'] },
  { id: 'document_shredding', name: 'Document Shredding', category: 'B2B Services', searchTerms: ['document shredding service', 'paper shredding', 'secure shredding'] },
  { id: 'uniform_supply', name: 'Uniform / Linen Supply', category: 'B2B Services', searchTerms: ['uniform supply', 'linen service', 'uniform rental'] },
  { id: 'vending_service', name: 'Vending Machine Service', category: 'B2B Services', searchTerms: ['vending machine service', 'vending company', 'office vending'] },
  { id: 'pos_systems', name: 'POS System Provider', category: 'B2B Services', searchTerms: ['POS system provider', 'point of sale system', 'restaurant POS'] },
  { id: 'merchant_services', name: 'Merchant / Payment Processing', category: 'B2B Services', searchTerms: ['merchant services', 'payment processing', 'credit card processing'] },
  { id: 'commercial_painting', name: 'Commercial Painter', category: 'B2B Services', searchTerms: ['commercial painting', 'commercial painter', 'office painting'] },
  { id: 'commercial_flooring', name: 'Commercial Flooring', category: 'B2B Services', searchTerms: ['commercial flooring', 'commercial carpet', 'office flooring'] },
  { id: 'waste_management', name: 'Waste Management / Recycling', category: 'B2B Services', searchTerms: ['waste management', 'commercial recycling', 'business waste removal'] },
  { id: 'business_telecom', name: 'Business Telecom / Phone', category: 'B2B Services', searchTerms: ['business phone system', 'VoIP provider', 'business telecom'] },
  { id: 'background_checks', name: 'Background Check Service', category: 'B2B Services', searchTerms: ['background check service', 'employee screening', 'pre-employment screening'] },
  { id: 'corporate_training', name: 'Corporate Training', category: 'B2B Services', searchTerms: ['corporate training', 'employee training', 'workplace training'] },
  { id: 'commercial_roofing', name: 'Commercial Roofing', category: 'B2B Services', searchTerms: ['commercial roofing', 'flat roof repair', 'commercial roof contractor'] },
  { id: 'commercial_door', name: 'Commercial Door Service', category: 'B2B Services', searchTerms: ['commercial door repair', 'automatic door service', 'commercial door installer'] },

  // ── Health & Wellness (expanded) ─────────────────────────────────────────
  { id: 'allergist', name: 'Allergist', category: 'Health & Wellness', searchTerms: ['allergist near me', 'allergy doctor', 'allergy clinic'] },
  { id: 'ent_doctor', name: 'ENT Doctor', category: 'Health & Wellness', searchTerms: ['ENT doctor', 'ear nose throat', 'ENT specialist'] },
  { id: 'sports_medicine', name: 'Sports Medicine', category: 'Health & Wellness', searchTerms: ['sports medicine doctor', 'sports injury clinic', 'sports medicine near me'] },
  { id: 'psychiatrist', name: 'Psychiatrist', category: 'Health & Wellness', searchTerms: ['psychiatrist near me', 'psychiatric clinic', 'mental health doctor'] },
  { id: 'fertility_clinic', name: 'Fertility Clinic', category: 'Health & Wellness', searchTerms: ['fertility clinic', 'IVF clinic', 'reproductive specialist'] },
  { id: 'iv_therapy', name: 'IV Therapy / Vitamin Infusion', category: 'Health & Wellness', searchTerms: ['IV therapy', 'vitamin infusion', 'IV drip bar'] },
  { id: 'cryotherapy', name: 'Cryotherapy', category: 'Health & Wellness', searchTerms: ['cryotherapy near me', 'cryo chamber', 'whole body cryotherapy'] },
  { id: 'float_tank', name: 'Float Tank / Sensory Deprivation', category: 'Health & Wellness', searchTerms: ['float tank', 'sensory deprivation tank', 'float therapy'] },
  { id: 'pelvic_floor', name: 'Pelvic Floor Therapist', category: 'Health & Wellness', searchTerms: ['pelvic floor therapy', 'pelvic floor specialist', 'pelvic rehab'] },
  { id: 'hypnotherapist', name: 'Hypnotherapist', category: 'Health & Wellness', searchTerms: ['hypnotherapist near me', 'hypnotherapy', 'clinical hypnosis'] },
  { id: 'addiction_counselor', name: 'Addiction Counselor', category: 'Health & Wellness', searchTerms: ['addiction counselor', 'substance abuse counselor', 'addiction treatment'] },
  { id: 'pain_management', name: 'Pain Management Clinic', category: 'Health & Wellness', searchTerms: ['pain management clinic', 'pain specialist', 'chronic pain doctor'] },
  { id: 'sleep_clinic', name: 'Sleep Clinic', category: 'Health & Wellness', searchTerms: ['sleep clinic', 'sleep disorder center', 'sleep study'] },
  { id: 'functional_medicine', name: 'Functional Medicine', category: 'Health & Wellness', searchTerms: ['functional medicine doctor', 'integrative medicine', 'holistic doctor'] },
  { id: 'wellness_coach', name: 'Wellness Coach', category: 'Health & Wellness', searchTerms: ['wellness coach', 'health coach', 'wellness coaching'] },
  { id: 'prenatal_care', name: 'Prenatal / Postnatal Care', category: 'Health & Wellness', searchTerms: ['prenatal care', 'midwife near me', 'postnatal care'] },
  { id: 'periodontist', name: 'Periodontist', category: 'Health & Wellness', searchTerms: ['periodontist near me', 'gum specialist', 'periodontal treatment'] },
  { id: 'endodontist', name: 'Endodontist', category: 'Health & Wellness', searchTerms: ['endodontist near me', 'root canal specialist', 'endodontic treatment'] },
  { id: 'home_health', name: 'Home Health Aide', category: 'Health & Wellness', searchTerms: ['home health aide', 'home health care', 'in-home nursing'] },
  { id: 'reiki_healer', name: 'Reiki / Energy Healer', category: 'Health & Wellness', searchTerms: ['reiki healer', 'energy healing', 'reiki practitioner'] },
  { id: 'marriage_therapist', name: 'Marriage / Family Therapist', category: 'Health & Wellness', searchTerms: ['marriage counselor', 'family therapist', 'couples therapy'] },
  { id: 'ophthalmologist', name: 'Ophthalmologist', category: 'Health & Wellness', searchTerms: ['ophthalmologist near me', 'eye surgeon', 'eye specialist'] },
  { id: 'prosthodontist', name: 'Prosthodontist', category: 'Health & Wellness', searchTerms: ['prosthodontist near me', 'dental implant specialist', 'dentures specialist'] },
  { id: 'lymphatic_drainage', name: 'Lymphatic Drainage', category: 'Health & Wellness', searchTerms: ['lymphatic drainage massage', 'lymphatic therapy', 'manual lymphatic drainage'] },

  // ── Beauty & Personal Care (expanded) ────────────────────────────────────
  { id: 'microblading', name: 'Microblading / Permanent Makeup', category: 'Beauty & Personal Care', searchTerms: ['microblading near me', 'permanent makeup', 'eyebrow tattoo'] },
  { id: 'esthetician', name: 'Esthetician / Skin Care', category: 'Beauty & Personal Care', searchTerms: ['esthetician near me', 'facial near me', 'skin care specialist'] },
  { id: 'hair_extensions', name: 'Hair Extensions Specialist', category: 'Beauty & Personal Care', searchTerms: ['hair extensions near me', 'hair extension salon', 'tape-in extensions'] },
  { id: 'braiding_salon', name: 'Braiding Salon', category: 'Beauty & Personal Care', searchTerms: ['braiding salon', 'African braiding', 'hair braiding near me'] },
  { id: 'body_contouring', name: 'Body Contouring / Sculpting', category: 'Beauty & Personal Care', searchTerms: ['body contouring', 'body sculpting', 'CoolSculpting near me'] },
  { id: 'scalp_treatment', name: 'Scalp Treatment / Trichologist', category: 'Beauty & Personal Care', searchTerms: ['trichologist near me', 'scalp treatment', 'hair loss treatment'] },
  { id: 'wig_specialist', name: 'Wig Shop / Specialist', category: 'Beauty & Personal Care', searchTerms: ['wig shop near me', 'wig specialist', 'custom wigs'] },
  { id: 'image_consultant', name: 'Image / Color Consultant', category: 'Beauty & Personal Care', searchTerms: ['image consultant', 'color analysis', 'personal stylist'] },
  { id: 'mobile_beauty', name: 'Mobile Beauty Service', category: 'Beauty & Personal Care', searchTerms: ['mobile beauty', 'mobile hair stylist', 'mobile nail tech'] },
  { id: 'dermaplaning', name: 'Dermaplaning / Chemical Peel', category: 'Beauty & Personal Care', searchTerms: ['dermaplaning near me', 'chemical peel', 'skin resurfacing'] },

  // ── Home Services (expanded) ─────────────────────────────────────────────
  { id: 'sprinkler_irrigation', name: 'Sprinkler / Irrigation', category: 'Home Services', searchTerms: ['sprinkler system', 'irrigation installer', 'lawn sprinkler repair'] },
  { id: 'hot_tub_service', name: 'Hot Tub / Spa Service', category: 'Home Services', searchTerms: ['hot tub service', 'spa repair', 'hot tub maintenance'] },
  { id: 'home_automation', name: 'Home Automation / Smart Home', category: 'Home Services', searchTerms: ['smart home installer', 'home automation', 'home theater installer'] },
  { id: 'mold_remediation', name: 'Mold Remediation', category: 'Home Services', searchTerms: ['mold remediation', 'mold removal', 'mold inspection'] },
  { id: 'radon_mitigation', name: 'Radon Testing / Mitigation', category: 'Home Services', searchTerms: ['radon testing', 'radon mitigation', 'radon removal'] },
  { id: 'paving_asphalt', name: 'Paving / Asphalt', category: 'Home Services', searchTerms: ['asphalt paving', 'driveway paving', 'asphalt contractor'] },
  { id: 'masonry', name: 'Masonry / Bricklayer', category: 'Home Services', searchTerms: ['masonry contractor', 'bricklayer near me', 'stone mason'] },
  { id: 'tile_installer', name: 'Tile Installer', category: 'Home Services', searchTerms: ['tile installer', 'tile contractor', 'backsplash installer'] },
  { id: 'countertop_installer', name: 'Countertop Installer', category: 'Home Services', searchTerms: ['countertop installer', 'granite countertops', 'quartz countertop'] },
  { id: 'cabinet_refacer', name: 'Cabinet Maker / Refacer', category: 'Home Services', searchTerms: ['cabinet maker', 'cabinet refacing', 'custom cabinets'] },
  { id: 'home_staging', name: 'Home Staging', category: 'Home Services', searchTerms: ['home staging service', 'house stager', 'real estate staging'] },
  { id: 'awning_installer', name: 'Awning Installer', category: 'Home Services', searchTerms: ['awning installer', 'retractable awning', 'patio awning'] },
  { id: 'screen_enclosure', name: 'Screen / Porch Enclosure', category: 'Home Services', searchTerms: ['screen enclosure', 'screened porch', 'patio enclosure'] },
  { id: 'wallpaper_installer', name: 'Wallpaper Installer', category: 'Home Services', searchTerms: ['wallpaper installer', 'wallpaper hanger', 'wall covering'] },
  { id: 'residential_security', name: 'Residential Security / Alarm', category: 'Home Services', searchTerms: ['home security system', 'home alarm installer', 'residential security'] },
  { id: 'stucco_contractor', name: 'Stucco Contractor', category: 'Home Services', searchTerms: ['stucco contractor', 'stucco repair', 'stucco application'] },
  { id: 'shower_door', name: 'Shower Door Installer', category: 'Home Services', searchTerms: ['shower door installer', 'frameless shower door', 'glass shower door'] },
  { id: 'crawl_space', name: 'Crawl Space Repair', category: 'Home Services', searchTerms: ['crawl space repair', 'crawl space encapsulation', 'crawl space moisture'] },

  // ── Automotive (expanded) ────────────────────────────────────────────────
  { id: 'window_tinting', name: 'Window Tinting', category: 'Automotive', searchTerms: ['window tinting', 'car window tint', 'auto tint near me'] },
  { id: 'paintless_dent', name: 'Paintless Dent Repair', category: 'Automotive', searchTerms: ['paintless dent repair', 'PDR near me', 'dent removal'] },
  { id: 'vehicle_wrap', name: 'Vehicle Wrap / Paint Protection', category: 'Automotive', searchTerms: ['vehicle wrap', 'car wrap', 'paint protection film'] },
  { id: 'diesel_mechanic', name: 'Diesel Mechanic', category: 'Automotive', searchTerms: ['diesel mechanic', 'diesel repair', 'diesel truck service'] },
  { id: 'ev_service', name: 'EV Repair / Service', category: 'Automotive', searchTerms: ['electric vehicle repair', 'EV service', 'EV charger installer'] },
  { id: 'alignment_shop', name: 'Alignment Shop', category: 'Automotive', searchTerms: ['wheel alignment', 'alignment shop', 'front end alignment'] },
  { id: 'muffler_exhaust', name: 'Muffler / Exhaust Shop', category: 'Automotive', searchTerms: ['muffler shop', 'exhaust repair', 'exhaust shop near me'] },
  { id: 'car_stereo', name: 'Car Stereo / Electronics', category: 'Automotive', searchTerms: ['car stereo installer', 'car audio', 'car electronics'] },
  { id: 'classic_car', name: 'Classic Car Restoration', category: 'Automotive', searchTerms: ['classic car restoration', 'vintage car repair', 'antique auto restoration'] },
  { id: 'golf_cart_service', name: 'Golf Cart Service', category: 'Automotive', searchTerms: ['golf cart repair', 'golf cart service', 'golf cart dealer'] },
  { id: 'atv_repair', name: 'ATV / UTV Repair', category: 'Automotive', searchTerms: ['ATV repair', 'UTV service', 'four wheeler repair'] },
  { id: 'trailer_repair', name: 'Trailer Repair', category: 'Automotive', searchTerms: ['trailer repair', 'trailer service', 'trailer maintenance'] },

  // ── Fitness & Recreation (expanded) ──────────────────────────────────────
  { id: 'barre_studio', name: 'Barre Studio', category: 'Fitness & Recreation', searchTerms: ['barre studio', 'barre class', 'barre fitness'] },
  { id: 'spin_studio', name: 'Spin / Cycling Studio', category: 'Fitness & Recreation', searchTerms: ['spin class', 'cycling studio', 'indoor cycling'] },
  { id: 'gymnastics', name: 'Gymnastics', category: 'Fitness & Recreation', searchTerms: ['gymnastics class', 'gymnastics gym', 'kids gymnastics'] },
  { id: 'horseback_riding', name: 'Horseback Riding / Equestrian', category: 'Fitness & Recreation', searchTerms: ['horseback riding lessons', 'equestrian center', 'riding school'] },
  { id: 'archery_range', name: 'Archery Range', category: 'Fitness & Recreation', searchTerms: ['archery range', 'archery lessons', 'archery club'] },
  { id: 'shooting_range', name: 'Shooting Range', category: 'Fitness & Recreation', searchTerms: ['shooting range near me', 'gun range', 'indoor shooting range'] },
  { id: 'trampoline_park', name: 'Trampoline Park', category: 'Fitness & Recreation', searchTerms: ['trampoline park', 'jump park', 'trampoline center'] },
  { id: 'paddleboard_kayak', name: 'Paddleboard / Kayak Rental', category: 'Fitness & Recreation', searchTerms: ['paddleboard rental', 'kayak rental', 'SUP rental'] },
  { id: 'scuba_school', name: 'Scuba Diving School', category: 'Fitness & Recreation', searchTerms: ['scuba diving lessons', 'PADI certification', 'scuba school'] },
  { id: 'skating_rink', name: 'Skating Rink', category: 'Fitness & Recreation', searchTerms: ['skating rink', 'roller skating', 'ice skating rink'] },
  { id: 'surf_school', name: 'Surf School', category: 'Fitness & Recreation', searchTerms: ['surf lessons', 'surf school', 'learn to surf'] },
  { id: 'boot_camp', name: 'Boot Camp Fitness', category: 'Fitness & Recreation', searchTerms: ['boot camp fitness', 'outdoor boot camp', 'fitness boot camp'] },
  { id: 'mini_golf', name: 'Mini Golf', category: 'Fitness & Recreation', searchTerms: ['mini golf', 'miniature golf', 'putt putt golf'] },
  { id: 'go_kart', name: 'Go-Kart Track', category: 'Fitness & Recreation', searchTerms: ['go kart track', 'go karting', 'indoor karting'] },
  { id: 'batting_cage', name: 'Batting Cage', category: 'Fitness & Recreation', searchTerms: ['batting cage', 'batting practice', 'hitting cages'] },

  // ── Pet Services (expanded) ──────────────────────────────────────────────
  { id: 'mobile_grooming', name: 'Mobile Pet Grooming', category: 'Pet Services', searchTerms: ['mobile pet grooming', 'mobile dog groomer', 'at-home pet grooming'] },
  { id: 'dog_daycare', name: 'Dog Daycare', category: 'Pet Services', searchTerms: ['dog daycare', 'doggy daycare', 'dog day care near me'] },
  { id: 'pet_waste_removal', name: 'Pet Waste Removal', category: 'Pet Services', searchTerms: ['pet waste removal', 'pooper scooper service', 'dog poop cleanup'] },
  { id: 'pet_bakery', name: 'Pet Bakery / Treat Shop', category: 'Pet Services', searchTerms: ['pet bakery', 'dog treat shop', 'gourmet pet treats'] },
  { id: 'aquarium_store', name: 'Aquarium / Fish Store', category: 'Pet Services', searchTerms: ['aquarium store', 'fish store', 'tropical fish shop'] },
  { id: 'pet_cremation', name: 'Pet Cremation / Memorial', category: 'Pet Services', searchTerms: ['pet cremation', 'pet memorial', 'pet funeral service'] },
  { id: 'pet_transport', name: 'Pet Taxi / Transport', category: 'Pet Services', searchTerms: ['pet transport', 'pet taxi', 'animal transport service'] },
  { id: 'exotic_vet', name: 'Exotic Animal Vet', category: 'Pet Services', searchTerms: ['exotic animal vet', 'reptile vet', 'avian vet'] },

  // ── Events & Creative (expanded) ─────────────────────────────────────────
  { id: 'photo_booth', name: 'Photo Booth Rental', category: 'Events & Creative', searchTerms: ['photo booth rental', 'event photo booth', 'selfie booth rental'] },
  { id: 'wedding_officiant', name: 'Wedding Officiant', category: 'Events & Creative', searchTerms: ['wedding officiant', 'marriage officiant', 'wedding minister'] },
  { id: 'face_painter', name: 'Face Painter', category: 'Events & Creative', searchTerms: ['face painter near me', 'face painting', 'kids face painter'] },
  { id: 'magician', name: 'Magician / Entertainer', category: 'Events & Creative', searchTerms: ['magician near me', 'party magician', 'kids entertainer'] },
  { id: 'custom_framing', name: 'Custom Framing', category: 'Events & Creative', searchTerms: ['custom framing', 'picture framing', 'frame shop'] },
  { id: 'calligrapher', name: 'Calligrapher', category: 'Events & Creative', searchTerms: ['calligrapher near me', 'calligraphy service', 'wedding calligraphy'] },
  { id: 'trophy_engraving', name: 'Trophy / Engraving Shop', category: 'Events & Creative', searchTerms: ['trophy shop', 'engraving service', 'awards and trophies'] },
  { id: 'muralist', name: 'Muralist / Wall Artist', category: 'Events & Creative', searchTerms: ['muralist near me', 'mural painter', 'wall mural artist'] },
  { id: 'invitation_shop', name: 'Invitation / Stationery', category: 'Events & Creative', searchTerms: ['wedding invitations', 'custom stationery', 'invitation shop'] },
  { id: 'gift_basket', name: 'Gift Basket Service', category: 'Events & Creative', searchTerms: ['gift basket delivery', 'custom gift baskets', 'gift basket service'] },
  { id: 'voiceover_artist', name: 'Voiceover Artist', category: 'Events & Creative', searchTerms: ['voiceover artist', 'voice actor', 'voiceover service'] },

  // ── Specialty Trades (expanded) ──────────────────────────────────────────
  { id: 'gunsmith', name: 'Gunsmith', category: 'Specialty Trades', searchTerms: ['gunsmith near me', 'gun repair', 'firearm service'] },
  { id: 'bicycle_repair', name: 'Bicycle Repair', category: 'Specialty Trades', searchTerms: ['bicycle repair', 'bike shop', 'bike mechanic'] },
  { id: 'piano_tuner', name: 'Piano Tuner', category: 'Specialty Trades', searchTerms: ['piano tuner near me', 'piano tuning', 'piano technician'] },
  { id: 'instrument_repair', name: 'Musical Instrument Repair', category: 'Specialty Trades', searchTerms: ['instrument repair', 'guitar repair', 'band instrument repair'] },
  { id: 'knife_sharpening', name: 'Knife Sharpening', category: 'Specialty Trades', searchTerms: ['knife sharpening service', 'blade sharpening', 'tool sharpening'] },
  { id: 'leather_repair', name: 'Leather Repair', category: 'Specialty Trades', searchTerms: ['leather repair', 'leather restoration', 'leather goods repair'] },
  { id: 'pool_table_service', name: 'Pool Table Service', category: 'Specialty Trades', searchTerms: ['pool table service', 'billiard table repair', 'pool table moving'] },
  { id: 'safe_vault', name: 'Safe / Vault Service', category: 'Specialty Trades', searchTerms: ['safe service', 'vault installation', 'safe cracking'] },
  { id: 'antenna_satellite', name: 'Antenna / Satellite Installer', category: 'Specialty Trades', searchTerms: ['satellite dish installer', 'antenna installation', 'TV antenna'] },
  { id: 'sewing_machine_repair', name: 'Sewing Machine Repair', category: 'Specialty Trades', searchTerms: ['sewing machine repair', 'sewing machine service', 'sewing repair'] },
  { id: 'vacuum_repair', name: 'Vacuum Repair', category: 'Specialty Trades', searchTerms: ['vacuum repair', 'vacuum cleaner service', 'vacuum shop'] },
  { id: 'camera_repair', name: 'Camera Repair', category: 'Specialty Trades', searchTerms: ['camera repair', 'camera service', 'lens repair'] },

  // ── Education & Childcare (expanded) ─────────────────────────────────────
  { id: 'nanny_agency', name: 'Nanny / Au Pair Agency', category: 'Education & Childcare', searchTerms: ['nanny agency', 'au pair agency', 'nanny service'] },
  { id: 'kids_cooking', name: 'Kids Cooking Class', category: 'Education & Childcare', searchTerms: ['kids cooking class', 'children cooking lessons', 'kids baking class'] },
  { id: 'kids_theater', name: 'Kids Theater / Drama', category: 'Education & Childcare', searchTerms: ['kids theater class', 'children drama', 'youth acting class'] },
  { id: 'college_counselor', name: 'College Counselor / Admissions', category: 'Education & Childcare', searchTerms: ['college counselor', 'college admissions consultant', 'college prep'] },
  { id: 'special_needs_ed', name: 'Special Needs Education', category: 'Education & Childcare', searchTerms: ['special needs education', 'special education tutor', 'learning disability support'] },
  { id: 'early_learning', name: 'Early Learning Center', category: 'Education & Childcare', searchTerms: ['early learning center', 'early childhood education', 'toddler program'] },

  // ── Cleaning & Maintenance (expanded) ────────────────────────────────────
  { id: 'grout_cleaning', name: 'Grout Cleaning / Tile Cleaning', category: 'Cleaning & Maintenance', searchTerms: ['grout cleaning', 'tile and grout cleaning', 'grout restoration'] },
  { id: 'biohazard_cleanup', name: 'Biohazard / Crime Scene Cleanup', category: 'Cleaning & Maintenance', searchTerms: ['biohazard cleanup', 'crime scene cleanup', 'trauma cleanup'] },
  { id: 'roof_cleaning', name: 'Roof Cleaning', category: 'Cleaning & Maintenance', searchTerms: ['roof cleaning', 'roof washing', 'moss removal roof'] },
  { id: 'construction_cleanup', name: 'Construction Cleanup', category: 'Cleaning & Maintenance', searchTerms: ['construction cleanup', 'post construction cleaning', 'builder clean'] },
  { id: 'dumpster_rental', name: 'Dumpster Rental', category: 'Cleaning & Maintenance', searchTerms: ['dumpster rental', 'roll off dumpster', 'construction dumpster'] },
  { id: 'hoarding_cleanup', name: 'Hoarding Cleanup', category: 'Cleaning & Maintenance', searchTerms: ['hoarding cleanup', 'hoarder clean out', 'hoarding help'] },
  { id: 'hood_cleaning', name: 'Hood / Vent Cleaning', category: 'Cleaning & Maintenance', searchTerms: ['hood cleaning service', 'kitchen exhaust cleaning', 'restaurant hood cleaning'] },
  { id: 'dryer_vent', name: 'Dryer Vent Cleaning', category: 'Cleaning & Maintenance', searchTerms: ['dryer vent cleaning', 'lint removal', 'dryer vent service'] },

  // ── Professional Services (expanded) ─────────────────────────────────────
  { id: 'bankruptcy_lawyer', name: 'Bankruptcy Lawyer', category: 'Professional Services', searchTerms: ['bankruptcy lawyer', 'bankruptcy attorney', 'debt relief lawyer'] },
  { id: 'criminal_defense', name: 'Criminal Defense Lawyer', category: 'Professional Services', searchTerms: ['criminal defense lawyer', 'criminal attorney', 'defense attorney'] },
  { id: 'dui_lawyer', name: 'DUI Lawyer', category: 'Professional Services', searchTerms: ['DUI lawyer', 'DUI attorney', 'drunk driving lawyer'] },
  { id: 'business_lawyer', name: 'Business / Corporate Lawyer', category: 'Professional Services', searchTerms: ['business lawyer', 'corporate attorney', 'business litigation'] },
  { id: 'patent_attorney', name: 'Patent / Trademark Attorney', category: 'Professional Services', searchTerms: ['patent attorney', 'trademark lawyer', 'intellectual property lawyer'] },
  { id: 'private_investigator', name: 'Private Investigator', category: 'Professional Services', searchTerms: ['private investigator', 'PI near me', 'private detective'] },
  { id: 'translator', name: 'Translator / Interpreter', category: 'Professional Services', searchTerms: ['translator near me', 'interpreter service', 'translation service'] },
  { id: 'resume_writer', name: 'Resume Writer / Career Coach', category: 'Professional Services', searchTerms: ['resume writer', 'career coach', 'resume writing service'] },
  { id: 'hr_consultant', name: 'HR Consultant', category: 'Professional Services', searchTerms: ['HR consultant', 'human resources consultant', 'HR outsourcing'] },
  { id: 'mediator', name: 'Mediator / Arbitrator', category: 'Professional Services', searchTerms: ['mediator near me', 'mediation service', 'dispute resolution'] },

  // ── Food & Hospitality (expanded) ────────────────────────────────────────
  { id: 'donut_shop', name: 'Donut Shop', category: 'Food & Hospitality', searchTerms: ['donut shop', 'doughnut shop', 'bakery donuts'] },
  { id: 'butcher_shop', name: 'Butcher Shop', category: 'Food & Hospitality', searchTerms: ['butcher shop near me', 'local butcher', 'meat market'] },
  { id: 'deli', name: 'Deli', category: 'Food & Hospitality', searchTerms: ['deli near me', 'delicatessen', 'sandwich shop'] },
  { id: 'wine_shop', name: 'Wine Shop / Liquor Store', category: 'Food & Hospitality', searchTerms: ['wine shop', 'liquor store', 'wine store near me'] },
  { id: 'candy_shop', name: 'Candy / Chocolate Shop', category: 'Food & Hospitality', searchTerms: ['candy shop', 'chocolate shop', 'confectionery'] },
  { id: 'tea_house', name: 'Tea House', category: 'Food & Hospitality', searchTerms: ['tea house', 'tea room', 'bubble tea shop'] },
  { id: 'cooking_class', name: 'Cooking Class Studio', category: 'Food & Hospitality', searchTerms: ['cooking class', 'cooking school', 'culinary class'] },
  { id: 'specialty_grocery', name: 'Specialty Grocery', category: 'Food & Hospitality', searchTerms: ['specialty grocery', 'gourmet food store', 'organic grocery'] },

  // ── Senior Services (new category) ───────────────────────────────────────
  { id: 'home_care_aide', name: 'Home Care Aide', category: 'Senior Services', searchTerms: ['home care aide', 'senior home care', 'elderly care service'] },
  { id: 'senior_transport', name: 'Senior Transportation', category: 'Senior Services', searchTerms: ['senior transportation', 'elderly transport', 'non-emergency medical transport'] },
  { id: 'medical_alert', name: 'Medical Alert Systems', category: 'Senior Services', searchTerms: ['medical alert system', 'personal emergency response', 'life alert'] },
  { id: 'estate_sale', name: 'Estate Sale Company', category: 'Senior Services', searchTerms: ['estate sale company', 'estate liquidation', 'estate sale service'] },
  { id: 'senior_meal', name: 'Senior Meal Delivery', category: 'Senior Services', searchTerms: ['senior meal delivery', 'meals on wheels', 'elderly meal service'] },
  { id: 'senior_fitness', name: 'Senior Fitness Program', category: 'Senior Services', searchTerms: ['senior fitness', 'senior exercise class', 'elderly fitness program'] },
  { id: 'aging_in_place', name: 'Aging in Place / Home Modification', category: 'Senior Services', searchTerms: ['aging in place', 'senior home modification', 'grab bar installation'] },
  { id: 'senior_daycare', name: 'Adult Day Care', category: 'Senior Services', searchTerms: ['adult day care', 'senior day program', 'adult day services'] },

  // ── Wedding & Bridal (new category) ──────────────────────────────────────
  { id: 'bridal_shop', name: 'Bridal Boutique', category: 'Wedding & Bridal', searchTerms: ['bridal shop', 'wedding dress shop', 'bridal boutique'] },
  { id: 'tuxedo_rental', name: 'Tuxedo Rental', category: 'Wedding & Bridal', searchTerms: ['tuxedo rental', 'suit rental', 'formal wear rental'] },
  { id: 'wedding_cake', name: 'Wedding Cake Baker', category: 'Wedding & Bridal', searchTerms: ['wedding cake baker', 'custom wedding cake', 'wedding cake near me'] },
  { id: 'wedding_limo', name: 'Wedding Limo / Transport', category: 'Wedding & Bridal', searchTerms: ['wedding limo', 'wedding transportation', 'bridal car service'] },
  { id: 'wedding_hair_makeup', name: 'Wedding Hair & Makeup', category: 'Wedding & Bridal', searchTerms: ['bridal hair and makeup', 'wedding makeup artist', 'wedding hair stylist'] },
  { id: 'wedding_favors', name: 'Wedding Favors / Gifts', category: 'Wedding & Bridal', searchTerms: ['wedding favors', 'wedding gifts', 'party favors'] },
  { id: 'rehearsal_dinner', name: 'Rehearsal Dinner Venue', category: 'Wedding & Bridal', searchTerms: ['rehearsal dinner venue', 'private dining room', 'rehearsal dinner restaurant'] },

  // ── Specialty Retail (new category) ──────────────────────────────────────
  { id: 'gift_shop', name: 'Gift Shop', category: 'Specialty Retail', searchTerms: ['gift shop near me', 'local gift store', 'unique gifts'] },
  { id: 'antique_dealer', name: 'Antique Dealer', category: 'Specialty Retail', searchTerms: ['antique dealer', 'antique shop', 'antique store near me'] },
  { id: 'consignment_shop', name: 'Consignment Shop', category: 'Specialty Retail', searchTerms: ['consignment shop', 'consignment store', 'resale shop'] },
  { id: 'pawn_shop', name: 'Pawn Shop', category: 'Specialty Retail', searchTerms: ['pawn shop near me', 'pawn broker', 'pawn store'] },
  { id: 'coin_dealer', name: 'Coin / Stamp Dealer', category: 'Specialty Retail', searchTerms: ['coin dealer', 'coin shop', 'stamp dealer'] },
  { id: 'vape_shop', name: 'Vape / Smoke Shop', category: 'Specialty Retail', searchTerms: ['vape shop', 'smoke shop', 'vaporizer store'] },
  { id: 'craft_supply', name: 'Craft Supply Store', category: 'Specialty Retail', searchTerms: ['craft supply store', 'hobby shop', 'craft store near me'] },
  { id: 'musical_instrument_store', name: 'Musical Instrument Store', category: 'Specialty Retail', searchTerms: ['music store', 'instrument shop', 'guitar store'] },
  { id: 'thrift_store', name: 'Thrift Store', category: 'Specialty Retail', searchTerms: ['thrift store near me', 'thrift shop', 'secondhand store'] },
  { id: 'comic_book_store', name: 'Comic Book / Game Store', category: 'Specialty Retail', searchTerms: ['comic book store', 'game store', 'tabletop game shop'] },

  // ── Travel & Transport (new category) ────────────────────────────────────
  { id: 'travel_agent', name: 'Travel Agent', category: 'Travel & Transport', searchTerms: ['travel agent near me', 'travel agency', 'vacation planner'] },
  { id: 'passport_service', name: 'Passport / Visa Service', category: 'Travel & Transport', searchTerms: ['passport service', 'visa service', 'passport expediting'] },
  { id: 'limo_service', name: 'Limo / Car Service', category: 'Travel & Transport', searchTerms: ['limo service', 'car service', 'chauffeur service'] },
  { id: 'airport_shuttle', name: 'Airport Shuttle', category: 'Travel & Transport', searchTerms: ['airport shuttle', 'airport transport', 'airport car service'] },
  { id: 'charter_bus', name: 'Charter Bus / Van', category: 'Travel & Transport', searchTerms: ['charter bus', 'charter van', 'group transportation'] },

  // ── Legal Support (new category) ─────────────────────────────────────────
  { id: 'bail_bonds', name: 'Bail Bonds', category: 'Legal Support', searchTerms: ['bail bonds near me', 'bail bondsman', 'bail agent'] },
  { id: 'process_server', name: 'Process Server', category: 'Legal Support', searchTerms: ['process server', 'legal process service', 'court document delivery'] },
  { id: 'court_reporter', name: 'Court Reporter', category: 'Legal Support', searchTerms: ['court reporter', 'legal transcription', 'deposition reporter'] },
  { id: 'legal_document', name: 'Legal Document Preparation', category: 'Legal Support', searchTerms: ['legal document preparation', 'legal forms service', 'document filing service'] },
  { id: 'polygraph', name: 'Polygraph / Lie Detector', category: 'Legal Support', searchTerms: ['polygraph test', 'lie detector test', 'polygraph examiner'] },

  // ── Agriculture & Rural (new category) ───────────────────────────────────
  { id: 'farrier', name: 'Farrier', category: 'Agriculture & Rural', searchTerms: ['farrier near me', 'horseshoeing', 'horse hoof care'] },
  { id: 'large_animal_vet', name: 'Large Animal Vet', category: 'Agriculture & Rural', searchTerms: ['large animal vet', 'equine vet', 'livestock veterinarian'] },
  { id: 'farm_equipment', name: 'Farm Equipment Repair', category: 'Agriculture & Rural', searchTerms: ['farm equipment repair', 'tractor repair', 'agricultural mechanic'] },
  { id: 'feed_store', name: 'Feed Store / Farm Supply', category: 'Agriculture & Rural', searchTerms: ['feed store', 'farm supply store', 'livestock feed'] },
  { id: 'fence_farm', name: 'Farm Fencing', category: 'Agriculture & Rural', searchTerms: ['farm fencing', 'ranch fencing', 'agricultural fence'] },
  { id: 'taxidermist', name: 'Taxidermist', category: 'Agriculture & Rural', searchTerms: ['taxidermist near me', 'taxidermy service', 'animal mounting'] },
];

export function getBusinessTypesByCategory(): Record<string, BusinessType[]> {
  const grouped: Record<string, BusinessType[]> = {};
  for (const bt of BUSINESS_TYPES) {
    if (!grouped[bt.category]) grouped[bt.category] = [];
    grouped[bt.category].push(bt);
  }
  return grouped;
}
